default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
   desc "Submit a new Beta Build to Firebase"
    lane :beta do
      gradle(task: "assembleDebug")
    end
  end
desc "Deploy to closed beta track"
lane :test_beta do
    build_android_app(task: "assembleRelease")
    firebase_app_distribution(
      app: ENV['1:872706339250:android:4a3af44a12cefaa0c2f4ab'],
      firebase_cli_token: ENV['1//0gkD2kKW1kQXFCgYIARAAGBASNwF-L9IrYxVtlaLm-5NUY2vSdD-ycHu9_HtOCr4rcXsSAQVbpcWBm7fkHi_P0zsX58JsI3qHb0I'],
      testers: "er.yugam@gmail.com",
      groups: "Test Demo Group1",
      release_notes: "RELEASE-NOTE",
      apk_path: "../build/outputs/apk/release/app-release.apk"
    )
end
 